[build-system]
requires = ["setuptools>=61.0.0", "wheel", "setuptools-git-versioning<2"]
build-backend = "setuptools.build_meta"

[project]
name = "zigpy-cli"
dynamic = ["version"]
description = "Unified command line interface for zigpy radios"
urls = {repository = "https://github.com/zigpy/zigpy-cli"}
authors = [
    {name = "puddly", email = "puddly3@gmail.com"}
]
readme = "README.md"
license = {text = "GPL-3.0"}
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
    "coloredlogs>=15.0",
    "scapy>=2.5.0",
    "zigpy>=0.85.0",
    "bellows>=0.47.0",
    "zigpy-deconz>=0.25.0",
    "zigpy-xbee>=0.21.0",
    "zigpy-zboss>=1.2.0",
    "zigpy-zigate>=0.14.0",
    "zigpy-znp>=1.0.0"
]

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*"]

[dependency-groups]
testing = [
    "coverage[toml]>=7.0",
    "pre-commit>=3.5",
    "pytest>=8.4",
    "pytest-asyncio>=1.0",
    "pytest-cov>=5.0",
    "pytest-mock>=3.14",
    "pytest-timeout>=2.3",
]
ci = [
    {include-group = "testing"},
    "pytest-github-actions-annotate-failures>=0.2",
    "pytest-xdist>=3.5",
]

[tool.setuptools-git-versioning]
enabled = true

[project.scripts]
zigpy = "zigpy_cli.__main__:cli"


[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]
src = ["zigpy_cli", "tests"]

[tool.ruff.isort]
known-first-party = ["zigpy_cli", "tests"]
