name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request: ~

jobs:
  shared-ci:
    uses: zigpy/workflows/.github/workflows/ci.yml@dm/updates-for-toml
    with:
      CODE_FOLDER: zigpy_cli
      CACHE_VERSION: 2
      PYTHON_VERSION_DEFAULT: 3.8.14
      PRE_COMMIT_CACHE_PATH:  ~/.cache/pre-commit
      MINIMUM_COVERAGE_PERCENTAGE: 98